#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Create python list of different user agent classes.

Data from http://www.user-agents.org/
XML: http://www.user-agents.org/allagents.xml
Date of allagents.xml: 06/19/2010

User agent TYPES:

B = Browser 
C = Link-, bookmark-, server- checking
D = Downloading tool
P = Proxy server, web filtering
R = Robot, crawler, spider 
S = Spam or bad bot

"""

ALLAGENTS_FILE = "allagents.xml.gz"
TARGET_FILEPATH = '../useragents.py'

TYPES = {
    'browser' : [],
    'linkchecker' : [],
    'downloader' : [],
    'proxy' : [],
    'robot' : [],
    'badbot' : []
}

def get_text(nodelist):
    """ get_text helper from 
    http://docs.python.org/library/xml.dom.minidom.html#dom-example
    """
    rc = []
    for node in nodelist:
        if node.nodeType == node.TEXT_NODE:
            rc.append(node.data)
    return ''.join(rc)

def handle_user_agent(user_agent):
    """ Handle on user-agent element. Dispatch on type.
    """
    ua_type = get_text(user_agent.getElementsByTagName("Type")[0].childNodes)
    ua_string = get_text(
        user_agent.getElementsByTagName("String")[0].childNodes)

    if ua_type == "B":
        TYPES['browser'].append(ua_string)
    elif ua_type == "C":
        TYPES['linkchecker'].append(ua_string)
    elif ua_type == "D":
        TYPES['downloader'].append(ua_string)
    elif ua_type == "P":
        TYPES['proxy'].append(ua_string)
    elif ua_type == "R":
        TYPES['robot'].append(ua_string)
    elif ua_type == "S":
        TYPES['badbot'].append(ua_string)

def handle_user_agents(user_agents):
    """ Handle root element. 
    """
    for user_agent in user_agents.getElementsByTagName("user-agent"):
        handle_user_agent(user_agent)

def main():
    """ Parse xml (possibly gzipped), fill up the datastructures and
    dump useragents.py (or specified TARGET_FILEPATH). This whole
    file should be run 'standalone'.
    """
    import pprint   
    import datetime
    from xml.dom.minidom import parse

    if ALLAGENTS_FILE.endswith("gz"):
        import gzip
        dom = parse(gzip.open(ALLAGENTS_FILE))
    else:
        dom = parse(ALLAGENTS_FILE)

    handle_user_agents(dom)

    prettyprinter = pprint.PrettyPrinter(width=80)

    handle = open(TARGET_FILEPATH, "w")

    handle.write("# -*- coding: utf-8 -*-\n")
    handle.write("""
    # Autogenerated useragent list (python make_useragents.py).

    # From http://www.user-agents.org/
    # http://www.user-agents.org/allagents.xml
    # 
    # Generated: %(now)s

    """ % { 'now' : datetime.datetime.utcnow().isoformat(' ') })

    handle.write("__all__ = ['browser', 'linkchecker', 'downloader', 'proxy', \
    'robot', 'badbot', 'useragents']\n\n")

    for key, value in TYPES.items():
        handle.write("%s = %s\n\n" % (key, prettyprinter.pformat(value)))

    handle.write("useragents = %s\n\n" % ', '.join(TYPES.keys()))
    handle.close()

if __name__ == '__main__':
    main()
